# -*- coding: utf-8 -*-
"""unemployment2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YBosAqAxIRVodi6dpnFmE3_Edcn3QxXR
"""

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")

df.columns =['States','Date','Frequency','Estimated Unemployment Rate','Estimated Employed','Estimated Labour Participation Rate','Region','longitude','latitude']

df['Date'] = pd.to_datetime(df['Date'],dayfirst=True)
df['Frequency']= df['Frequency'].astype('category')
df['Month'] =  df['Date'].dt.month
df['Month_int'] = df['Month'].apply(lambda x : int(x))
df['Region'] = df['Region'].astype('category')
df.drop(columns='Month',inplace=True)

fig = px.box(df,x='States',y='Estimated Unemployment Rate',color='States',title='Unemployment rate',template='plotly')
fig.update_layout(xaxis={'categoryorder':'total descending'})
fig.show()

plot_unemp = df[['Estimated Unemployment Rate','States']]

df_unemp = plot_unemp.groupby('States').mean().reset_index()

df_unemp = df_unemp.sort_values('Estimated Unemployment Rate')

fig = px.bar(df_unemp, x='States',y='Estimated Unemployment Rate',color='States',
            title='Average Unemployment Rate in each state',template='plotly')

fig.show()

unemplo_df = df[['States','Region','Estimated Unemployment Rate','Estimated Employed','Estimated Labour Participation Rate']]

unemplo = unemplo_df.groupby(['Region','States'])['Estimated Unemployment Rate'].mean().reset_index()
fig = px.sunburst(unemplo, path=['Region','States'], values='Estimated Unemployment Rate', color_continuous_scale='Plasma',title= 'unemployment rate in each region and state',height=650,template='ggplot2')


fig.show()